language: go

branches:
  only:
    - master

go:
  - "1.10"

install:
  - go get -t -v ./... # all deps
  - go get -u github.com/golang/lint/golint
  - export PATH=$PATH:$HOME/.local/bin

script:
  - go tool vet .
  - golint -set_exit_status ./...
  - gofmt -l . | exit $(wc -l)
  - go test -v -cover -race -benchmem -bench .

notifications:
  slack:
    rooms:
        - panoplyio:LeK4hoOIDsRiBBAhgXKnSAD0#builds
    on_pull_requests: false
    on_success: change
    on_failure: always
  email:
    recipients:
      - hackers@panoply.io
    on_success: change
    on_failure: always
